### ISSUE TITLE
How to "convert" fonts?

### ISSUE THREAD

**Issue by sabino** [jonathan-reisdorf/node-onion-omega-oled-text#6]
Hey @jonathan-reisdorf! Great work!

I was messing around here with my Omega2+ and found a program called [GLCD Font Creator](http://www.mikroe.com/supporting-software/#/)
![mikroelektronika-glcd-font-creator-software](https://cloud.githubusercontent.com/assets/982190/26387131/840dabaa-4021-11e7-8035-6fffbc3b3426.jpg)

And looks like it basically is a font editor that allows you to set the device size. So I was trying to export but I've noticed that the HEX formats are different. Do you have any convertion table you've used for converting the current script font?

Oh, and I've found a bunch of fonts 16x16 that can be used [here](http://www.rinkydinkelectronics.com/r_fonts.php) since its Public Domain.

I can make script that would allow anyone to convert but I need to know how you did it.

Thanks!

**Comment by jonathan-reisdorf** [comment]
Hi Felipe, thanks for asking. :)
I have already provided a character editor here: https://github.com/jonathan-reisdorf/node-onion-omega-oled-text/blob/master/editor.html

Does that work for your needs? If you want to write a font converter, feel free to use code from there. The display of the omega2 works a little bit different than usual. More details here: https://docs.onion.io/omega2-docs/oled-expansion.html

Also feel free to ask further questions :)
