### ISSUE TITLE
character editor not working

### ISSUE THREAD

**Issue by ThisInsider** [jonathan-reisdorf/node-onion-omega-oled-text#7]
Hi, I'm working on a project that's heavily based on your code.

I stumbled upon your character editor and I just can't get it to work. I tried every browser and even triple-checked if js is enabled.

Also, if I define a character that already exists, such as a 0 for example, does it automatically get "overwritten"?

Thanks for your help!

**Comment by jonathan-reisdorf** [comment]
Hi, sorry for the extremely late response 😅 It won't be relevant for you anymore by now, but I just tested that the character editor works simply by opening the editor.html file in a browser (tested with latest Chrome + Firefox). Let me know in case this should still be a relevant issue for you and the editor still does not work. And yes, using `addCharacter` and specifying an existing character would replace it with the new byteMatrix.

**Comment by ThisInsider** [comment]
I don't even remember what I needed it for... but I think I found a workaround... I think... xD
